// Generated by CoffeeScript 1.10.0
(function() {
  var navTags, renderList, renderObject, selectedObj;

  navTags = [];

  selectedObj = void 0;

  renderList = function() {
    var dragObj, i, len, navElem, navItem, objList, propPanel, renderNavItem, tagList;
    objList = document.getElementById('objectList');
    tagList = document.getElementById('tagList');
    navElem = document.getElementById('navTags');
    propPanel = document.getElementById('propertiesPanel');
    dragObj = void 0;
    renderNavItem = function(item) {
      var navItem;
      navItem = document.createElement('div');
      navItem.className = 'navTag';
      navItem.textContent = item;
      navElem.appendChild(navItem);
      return navItem.addEventListener('click', function() {
        var index;
        index = navTags.indexOf(item);
        navTags.splice(index, 1);
        return renderList();
      });
    };
    objList.innerHTML = '';
    tagList.innerHTML = '';
    navElem.innerHTML = '';
    propPanel.style.visibility = 'hidden';
    for (i = 0, len = navTags.length; i < len; i++) {
      navItem = navTags[i];
      renderNavItem(navItem);
    }
    return tagging.forObjectsAndTags((function(obj) {
      var element, j, len1, nameElement, ref, tag, tagElement, tagsElement;
      element = document.createElement('div');
      nameElement = document.createElement('span');
      tagsElement = document.createElement('span');
      if (obj === selectedObj) {
        element.className = 'listObject selected';
        propPanel.style.visibility = 'visible';
      } else {
        element.className = 'listObject';
      }
      element.setAttribute('draggable', 'true');
      element.addEventListener('dragstart', function(e) {
        dragObj = obj;
        return e.dataTransfer.setData('text/plain', 'object');
      });
      nameElement.textContent = obj.name;
      nameElement.className = 'listObjectName';
      ref = obj.tags;
      for (j = 0, len1 = ref.length; j < len1; j++) {
        tag = ref[j];
        tagElement = document.createElement('span');
        tagElement.className = 'listObjectTag';
        tagElement.textContent = tag;
        tagsElement.appendChild(tagElement);
      }
      element.appendChild(nameElement);
      element.appendChild(tagsElement);
      objList.appendChild(element);
      return element.addEventListener('click', function() {
        var k, len2, listObj, ref1;
        ref1 = element.parentNode.childNodes;
        for (k = 0, len2 = ref1.length; k < len2; k++) {
          listObj = ref1[k];
          listObj.className = 'listObject';
        }
        element.className = 'listObject selected';
        selectedObj = obj;
        return renderObject(obj);
      });
    }), (function(tag) {
      var element, j, len1, nameElement, otherItem, removeItem;
      element = document.createElement('div');
      nameElement = document.createElement('span');
      element.className = 'listTag';
      element.addEventListener('dragover', function(e) {
        if (dragObj.tags.indexOf(tag) === -1) {
          return e.preventDefault();
        }
      });
      element.addEventListener('dragenter', function() {
        if (dragObj.tags.indexOf(tag) === -1) {
          return element.className = 'listTag dragtarget';
        }
      });
      element.addEventListener('dragleave', function() {
        return element.className = 'listTag';
      });
      element.addEventListener('drop', function(e) {
        if (dragObj.tags.indexOf(tag) === -1) {
          tagging.addTag(dragObj, tag);
          renderList();
          if (dragObj === selectedObj) {
            renderObject(selectedObj);
          }
        }
        return e.preventDefault();
      });
      for (j = 0, len1 = navTags.length; j < len1; j++) {
        otherItem = navTags[j];
        if (otherItem.length < tag.length - 1 && tag.substr(0, otherItem.length) === otherItem && tag[otherItem.length] === '/') {
          removeItem = otherItem;
          break;
        }
      }
      nameElement.textContent = tag;
      nameElement.className = 'listTagName';
      element.appendChild(nameElement);
      element.addEventListener('click', function() {
        navTags.splice(navTags.indexOf(removeItem), 1);
        navTags.push(tag);
        return renderList();
      });
      return tagList.appendChild(element);
    }), navTags);
  };

  renderObject = function(obj) {
    var objClone, objTags;
    objTags = document.getElementById('objTags');
    objClone = objTags.cloneNode(false);
    document.getElementById('propertiesPanel').style.visibility = 'visible';
    document.getElementById('objName').textContent = obj.name;
    objTags.parentNode.replaceChild(objClone, objTags);
    objTags = objClone;
    tagbox(objTags, tagging.matchingTags);
    objTags.setTags(obj.tags);
    objTags.addEventListener('tagadded', function(e) {
      tagging.addTag(obj, e.detail);
      return renderList();
    });
    return objTags.addEventListener('tagremoved', function(e) {
      tagging.removeTag(obj, e.detail);
      return renderList();
    });
  };

  document.addEventListener('DOMContentLoaded', function() {
    var addButton;
    addButton = document.getElementById('addObject');
    addButton.addEventListener('click', function() {
      var name, obj;
      name = prompt('Name of object?');
      obj = {
        name: name,
        tags: navTags.slice()
      };
      tagging.addObject(obj);
      selectedObj = obj;
      renderList();
      return renderObject(obj);
    });
    return renderList();
  });

}).call(this);

//# sourceMappingURL=main.js.map
