// Generated by CoffeeScript 1.9.3
(function() {
  window.tagcomplete = function(elem, listCallback) {
    var createList, listElem;
    listElem = document.createElement("datalist");
    elem.parentNode.insertBefore(listElem, elem.nextSibling);
    listElem.id = "list1337";
    elem.setAttribute("list", "list1337");
    createList = function(list) {
      var curOption, i, itemElem, j, results;
      list.sort();
      i = 0;
      j = 0;
      while (i < list.length && j < listElem.childNodes.length) {
        curOption = listElem.childNodes.item(j);
        if (list[i] < curOption.value) {
          itemElem = document.createElement("option");
          itemElem.value = list[i];
          listElem.insertBefore(itemElem, curOption);
          i += 1;
          j += 1;
        } else if (list[i] > curOption.value) {
          listElem.removeChild(curOption);
        } else {
          i += 1;
          j += 1;
        }
      }
      while (j < listElem.childNodes.length) {
        listElem.removeChild(listElem.childNodes.item(j));
      }
      results = [];
      while (i < list.length) {
        itemElem = document.createElement("option");
        itemElem.value = list[i];
        listElem.appendChild(itemElem);
        results.push(i += 1);
      }
      return results;
    };
    return elem.addEventListener("input", function() {
      if (elem.value.length > 0) {
        return listCallback(elem.value, createList);
      } else {
        return listElem.innerHTML = "";
      }
    });
  };

}).call(this);

//# sourceMappingURL=tagcomplete.js.map
